from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional, Union, Literal
from datetime import datetime

NEWS_CATEGORIES_TYPES = [
    'Alimentação & Gastronomia',
    'Ciência & Tecnologia',
    'Costumes',
    'Economia',
    'Educação',
    'Entretenimento & Cultura Pop',
    'Esportes',
    'Geopolítica & Relações Internacionais',
    'Justiça Social',
    'Meio Ambiente',
    'Negócios & Empreendedorismo',
    'Política',
    'Religião',
    'Saúde & Bem-estar',
    'Segurança & Crime',
    'Transporte & Mobilidade',
    'Outros'
]

class TreatmentType(Enum):
    HUMAN = 'human'
    MACHINE = 'machine'

class ParticipantStatus(Enum):
    NEW = 'new'
    IN_PROGRESS_ANSWER1_P1 = 'in_progress_a1_1'
    IN_PROGRESS_ANSWER1_P2 = 'in_progress_a1_2'
    IN_PROGRESS_ANSWER2_P1 = 'in_progress_a2_1'
    IN_PROGRESS_ANSWER2_P2 = 'in_progress_a2_2'
    IN_PROGRESS_ANSWER3_P1 = 'in_progress_a3_1'
    IN_PROGRESS_ANSWER3_P2 = 'in_progress_a3_2'
    IN_PROGRESS_ANSWER4_P1 = 'in_progress_a4_1'
    IN_PROGRESS_ANSWER4_P2 = 'in_progress_a4_2'
    COMPLETED = 'completed'

class Singleton(object):
    _instance = None
    def __new__(class_, *args, **kwargs):
        if not isinstance(class_._instance, class_):
            class_._instance = object.__new__(class_, *args, **kwargs)
        return class_._instance


class BlockComponent(BaseModel):
    # type: str = Field(..., discriminator=True)
    # type: BlockType = Field(..., description="Type of the block, e.g., text, image, video")
    # content: str = Field(..., description="Content of the block, can be text, image URL, or video URL")
    # metadata: dict = Field(default_factory=dict, description="Additional metadata for the block, for example, image or video description")
    pass

class TextComponent(BlockComponent):
    type: Literal["text"] = "text"
    markdown_text: str = Field(..., description="Markdown formatted text content")
    links: list[str] = Field(default_factory=list, description="List of links in the text content")

class ImageComponent(BlockComponent):
    type: Literal["image"] = "image"
    data: str = Field(..., description="binary encoded image data")
    url: str = Field(..., description="URL of the image")
    transcript: TextComponent = Field(..., description="Transcript of the image, if available")

class VideoComponent(BlockComponent):
    type: Literal["video"] = "video"
    url: str = Field(..., description="URL of the video")
    transcript: TextComponent = Field(..., description="Transcript of the video, if available")

BlockComponentUnion = Union[TextComponent, ImageComponent, VideoComponent]

class NewsBlock(BaseModel):
    blocks: list[BlockComponentUnion] = Field(..., description="List of blocks in the news article")
    label: str = Field(..., description="Label of the news article, e.g., 'Verdadeiro', 'Falso'")

# Generated at phase 2 - Maintained at phase 3
class NewsVerificationCategorized(BaseModel):
    url: str = Field(..., description="URL of the news article")
    title: str = Field(..., description="Title of the news article")
    publication_date: Optional[datetime] = Field(..., description="Publication date of the news article in ISO format")
    old_category: str = Field(..., description="Category found from scrapping")
    category: str = Field(..., description="Category generated by grouping scrapped categories")
    blocks: list[NewsBlock] = Field(..., description="List of blocks in the news article")

# Generated at phase 4
class NewsVerificationImproved(BaseModel):
    url: str = Field(..., description="URL of the news article")
    title: str = Field(..., description="Title of the news article")
    llm_identified_news: str = Field(..., description="News identified by LLM based on the blocks provided")
    publication_date: Optional[datetime] = Field(..., description="Publication date of the news article in ISO format")
    old_category: str = Field(..., description="Category found from scrapping")
    category: str = Field(..., description="Category generated by grouping scrapped categories")
    blocks: list[NewsBlock] = Field(..., description="List of blocks in the news article")

    # Generated at phase 4
class NewsBlockWithLLMOutput(BaseModel):
    blocks: list[BlockComponentUnion] = Field(..., description="List of blocks in the news article")
    label: str = Field(..., description="Label of the news article, e.g., 'Verdadeiro', 'Falso'")
    llm_verdicts: list[str] = Field(..., description="LLM Verdict Labels")
    llm_agent_outputs: list[str] = Field(..., description="LLM Agent Verdicts explained")
    summarized_result: str | None = Field(..., description="LLM Summarization is defined if len(llm_agent_outpts) > 1")
    web_final_report: str = Field(..., description="Final Web Report for debugging purposes")

class NewsVerificationImprovedLLMOutput(BaseModel):
    url: str = Field(..., description="URL of the news article")
    title: str = Field(..., description="Title of the news article")
    llm_identified_news: str = Field(..., description="News identified by LLM based on the blocks provided")
    publication_date: Optional[datetime] = Field(..., description="Publication date of the news article in ISO format")
    old_category: str = Field(..., description="Category found from scrapping")
    category: str = Field(..., description="Category generated by grouping scrapped categories")
    blocks_with_llm_output: list[NewsBlockWithLLMOutput] = Field(..., description="List of blocks in the news article")